### ISSUE TITLE
mapValueObject on XML with multiple child nodes of same type

### ISSUE THREAD

**Issue by lorro** [sabre-io/xml#139]
Hi,

I'm having a struggle with reading a XML and structuring it with mapValueObject.
I have the following xml structure. As you can see a JobSet has multiple Job nodes.

```xml
<JobList>
   <JobSet>
         <Job></Job>
         <Job></Job>
         <Job></Job>
    </JobSet>
</JobList>
```
```php
$service->mapValueObject('{http://webservice.talentfinder.be}JobList', JobList::class);
$service->mapValueObject('{http://webservice.talentfinder.be}JobSet', JobSet::class);
$service->mapValueObject('{http://webservice.talentfinder.be}Job', Job::class);
```

It gets mapped correctly but if I inspect my php array I've got just one Job object in JobSet, instead of a bunch of them. Actually only the last is in the array. Probably this node gets overwritten while looping the XML?

Any idea what I could do to overcome this?

Thanks!

**Comment by evert** [comment]
Can you share the `JobSet` class?

**Comment by evert** [comment]
Great!
