### ISSUE TITLE
XML elements directly following <media:content xmlns:media="http://search.yahoo.com/mrss/" seem to be ignored when parsing.

### ISSUE THREAD

**Issue by xeiter** [sabre-io/xml#142]
When parsing XML like the following:

`<?xml version="1.0" encoding="UTF-8"?>
<entry xmlns="http://www.w3.org/2005/Atom">
    <media:content xmlns:media="http://search.yahoo.com/mrss/" url="https://some-url.com?AWSAccessKeyId=XYZ&amp;Expires=1531998005&amp;Signature=XYZ%3D" type="video/mp4" medium="video">
        <media:hash algo="md5">XYZ</media:hash>
    </media:content><media:thumbnail xmlns:media="http://search.yahoo.com/mrss/"
                     url="https://some-url.com/image/xyz.jpg" width="1755" height="987"/>
</entry>`

I noticed that the XML elements directly following the closure of **<media:content** get ignored and do not get parsed.

If I put a space or a new line right after the closure of **<media:content**, parsing for XML elements that follow works again.

In my example above, the **<media:thumbnail** element would not get parsed at all.

If I put a space or a new line before **<media:thumbnail** it gets parsed properly.

I tried replacing **<media:thumbnail** with other XML elements, the behaviour is the same.

**Comment by staabm** [comment]
How does your code look like?

**Comment by tsterker** [comment]
@staabm I am experiencing the same issue, but am currently not able to provide a minimal code example. I'll try to do so in the coming days.

---

My current workaround is to pretty-print all xml before passing it to my service's `parse` or `expect` method:

```php
function prettyPrint($xml)
{
  $domxml = new \DOMDocument('1.0', 'UTF-8');
  $domxml->preserveWhiteSpace = false;
  $domxml->formatOutput = true;
  $domxml->loadXML($xml);
  return $domxml->saveXML();
}
```

**Comment by tsterker** [comment]
@staabm @xeiter  **Update:**

In my case the issue was that I used both `$reader->parseInnterTree` and `$parser->next()` in the same element mapping, which the [documentation](http://sabre.io/xml/reading/) shows should not be done.

**Crude high level explanation of the observed behavior:**
Seems like whitespace between elements is treated as "empty text node", which the extra `next()` then jumps to, which masks the underlying problem of unintentionally moving the pointer forward.

So, without confirming my suspicion by delving into the code, I guess there is no bug after all.

---
**For completeness, example to reproduce behavior:**

```php
class ExampleService extends \Sabre\Xml\Service
{
    public function __construct()
    {
        $this->elementMap['child'] = function (\Sabre\Xml\Reader $reader) {
            $innter = $reader->parseInnerTree();
            $reader->next();

            return 'text';
        };
    }
}

$service = new BugExampleService;

$works = $service->parse("<root>
    <child></child>
    <child></child>
</root>");

$doesntWork = $service->parse("<root>
    <child></child><child></child>
</root>");
```

**Comment by evert** [comment]
I think one of the things that's a bit confusing in the current API is when to use `->next()`.

The general rule is that for any parser that parses an entire sub-tree, it also advances the pointer to the next element, but for any of the (manual-ish) read() functions this is not the case, and it's up to you to make sure that the XML reader pointer is set to the next element after parsing.

So I would be curious if @xeiter had a similar problem. I've definitely ran into this myself, but I don't really know how to improve the ergonomics of this.

**Comment by tsterker** [comment]
*Update:*

It seems that this issue also occurs for `mapValueObject`s.

I don't have much time digging into this right now, but hope this minimal example helps:

```php
class ExampleService extends \Sabre\Xml\Service
{
    public function __construct()
    {
        $this->mapValueObject("{}Child", Child::class);
    }
}

class Child
{
    public $One;
}

$service = new ExampleService;

$works = $service->parse("<root>
    <Child>
    </Child>
</root>");

$doesntWork = $service->parse("<root>
    <Child></Child>
</root>");
```

The latter `$doesntWork` example throws an Exception:

> "Uncaught Sabre\Xml\ParseException: We hit the end of the document prematurely."

**Comment by akubaragas** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xml:lang="en-US">
  <id>tag:github.com,2008:/akubaragas</id>
  <link type="text/html" rel="alternate" href="https://github.com/akubaragas"/>
  <link type="application/atom+xml" rel="self" href="https://github.com/akubaragas.private.atom?token=AUCQG5WJ2J4N34MXIKVYEFN6VTPKE"/>
  <title>Private Feed for akubaragas</title>
  <updated>2021-05-16T10:56:38Z</updated>
  <entry>
    <id>tag:github.com,2008:WatchEvent/16377146707</id>
    <published>2021-05-16T10:56:38Z</published>
    <updated>2021-05-16T10:56:38Z</updated>
    <link type="text/html" rel="alternate" href="https://github.com/SaijoGeorge/ExpandingGridItemAnimation"/>
    <title type="html">theemack starred SaijoGeorge/ExpandingGridItemAnimation</title>
    <author>
      <name>theemack</name>
      <uri>https://github.com/theemack</uri>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/7733293?s=30&amp;v=4"/>
    <content type="html">&lt;div class=&quot;watch_started&quot; data-test-selector=&quot;visible-event&quot;&gt;&lt;div class=&quot;body&quot;&gt;
&lt;!-- watch --&gt;
&lt;div class=&quot;d-flex flex-items-baseline border-bottom color-border-secondary py-3&quot;&gt;
    &lt;span class=&quot;mr-2&quot;&gt;&lt;a class=&quot;d-inline-block&quot; href=&quot;/theemack&quot; rel=&quot;noreferrer&quot;&gt;&lt;img class=&quot;avatar avatar-user&quot; src=&quot;https://avatars.githubusercontent.com/u/7733293?s=64&amp;amp;v=4&quot; width=&quot;32&quot; height=&quot;32&quot; alt=&quot;@theemack&quot;&gt;&lt;/a&gt;&lt;/span&gt;

  &lt;div class=&quot;d-flex flex-column width-full&quot;&gt;
      &lt;div&gt;
        &lt;div class=&quot;d-flex flex-items-baseline&quot;&gt;
          &lt;div&gt;
            &lt;a class=&quot;Link--primary no-underline text-bold wb-break-all d-inline-block&quot; href=&quot;/theemack&quot; rel=&quot;noreferrer&quot;&gt;theemack&lt;/a&gt;
            starred
            &lt;a class=&quot;Link--primary no-underline text-bold wb-break-all d-inline-block&quot; href=&quot;/SaijoGeorge/ExpandingGridItemAnimation&quot; rel=&quot;noreferrer&quot;&gt;SaijoGeorge/ExpandingGridItemAnimation&lt;/a&gt;
            &lt;span class=&quot;f6 color-text-tertiary no-wrap ml-1&quot;&gt;
              &lt;relative-time datetime=&quot;2021-05-16T10:56:38Z&quot; class=&quot;no-wrap&quot;&gt;May 16, 2021&lt;/relative-time&gt;
            &lt;/span&gt;
          &lt;/div&gt;
        &lt;/div&gt;
      &lt;/div&gt;

      &lt;div class=&quot;Box p-3 mt-2&quot;&gt;
        &lt;div&gt;
          &lt;div class=&quot;f4 lh-condensed text-bold color-text-primary&quot;&gt;
            &lt;a class=&quot;Link--primary no-underline text-bold wb-break-all d-inline-block&quot; href=&quot;/SaijoGeorge/ExpandingGridItemAnimation&quot; rel=&quot;noreferrer&quot;&gt;SaijoGeorge/ExpandingGridItemAnimation&lt;/a&gt;
          &lt;/div&gt;
          &lt;div class=&quot;dashboard-break-word color-text-secondary mt-1 mb-0 repo-description&quot;&gt;
            &lt;p&gt;Grid item animation based on the Dribbble shot &quot;Surf Project&quot; by Filip Slováček.&lt;/p&gt;
          &lt;/div&gt;

          &lt;p class=&quot;f6 color-text-secondary mt-2 mb-0&quot;&gt;
              &lt;span class=&quot;d-inline-block color-text-secondary mr-3&quot;&gt;
                &lt;span class=&quot;ml-0&quot;&gt;
  &lt;span class=&quot;repo-language-color&quot; style=&quot;background-color: #f1e05a&quot;&gt;&lt;/span&gt;
  &lt;span itemprop=&quot;programmingLanguage&quot;&gt;JavaScript&lt;/span&gt;
&lt;/span&gt;

              &lt;/span&gt;

              &lt;span class=&quot;d-inline-block mr-3&quot;&gt;
                  &lt;a class=&quot;Link--muted&quot; href=&quot;/SaijoGeorge/ExpandingGridItemAnimation/stargazers&quot; rel=&quot;noreferrer&quot;&gt;&lt;svg class=&quot;octicon octicon-star mr-1&quot; viewBox=&quot;0 0 16 16&quot; version=&quot;1.1&quot; width=&quot;16&quot; height=&quot;16&quot; aria-hidden=&quot;true&quot;&gt;&lt;path fill-rule=&quot;evenodd&quot; d=&quot;M8 .25a.75.75 0 01.673.418l1.882 3.815 4.21.612a.75.75 0 01.416 1.279l-3.046 2.97.719 4.192a.75.75 0 01-1.088.791L8 12.347l-3.766 1.98a.75.75 0 01-1.088-.79l.72-4.194L.818 6.374a.75.75 0 01.416-1.28l4.21-.611L7.327.668A.75.75 0 018 .25zm0 2.445L6.615 5.5a.75.75 0 01-.564.41l-3.097.45 2.24 2.184a.75.75 0 01.216.664l-.528 3.084 2.769-1.456a.75.75 0 01.698 0l2.77 1.456-.53-3.084a.75.75 0 01.216-.664l2.24-2.183-3.096-.45a.75.75 0 01-.564-.41L8 2.694v.001z&quot;&gt;&lt;/path&gt;&lt;/svg&gt;9&lt;/a&gt;
              &lt;/span&gt;


              &lt;span&gt;Updated May 16&lt;/span&gt;
          &lt;/p&gt;
        &lt;/div&gt;
      &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;&lt;/div&gt;</content>
  </entry>
  <entry>
    <id>tag:github.com,2008:WatchEvent/16377133437</id>
    <published>2021-05-16T10:52:51Z</published>
    <updated>2021-05-16T10:52:51Z</updated>
    <link type="text/html" rel="alternate" href="https://github.com/SaijoGeorge/ExpandingGridItemAnimation"/>
    <title type="html">theemack starred SaijoGeorge/ExpandingGridItemAnimation</title>
    <author>
      <name>theemack</name>
      <uri>https://github.com/theemack</uri>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/7733293?s=30&amp;v=4"/>
    <content type="html">&lt;div class=&quot;watch_started&quot; data-test-selector=&quot;visible-event&quot;&gt;&lt;div class=&quot;body&quot;&gt;
&lt;!-- watch --&gt;
&lt;div class=&quot;d-flex flex-items-baseline border-bottom color-border-secondary py-3&quot;&gt;
    &lt;span class=&quot;mr-2&quot;&gt;&lt;a class=&quot;d-inline-block&quot; href=&quot;/theemack&quot; rel=&quot;noreferrer&quot;&gt;&lt;img class=&quot;avatar avatar-user&quot; src=&quot;https://avatars.githubusercontent.com/u/7733293?s=64&amp;amp;v=4&quot; width=&quot;32&quot; height=&quot;32&quot; alt=&quot;@theemack&quot;&gt;&lt;/a&gt;&lt;/span&gt;

  &lt;div class=&quot;d-flex flex-column width-full&quot;&gt;
      &lt;div&gt;
        &lt;div class=&quot;d-flex flex-items-baseline&quot;&gt;
          &lt;div&gt;
            &lt;a class=&quot;Link--primary no-underline text-bold wb-break-all d-inline-block&quot; href=&quot;/theemack&quot; rel=&quot;noreferrer&quot;&gt;theemack&lt;/a&gt;
            starred
            &lt;a class=&quot;Link--primary no-underline text-bold wb-break-all d-inline-block&quot; href=&quot;/SaijoGeorge/ExpandingGridItemAnimation&quot; rel=&quot;noreferrer&quot;&gt;SaijoGeorge/ExpandingGridItemAnimation&lt;/a&gt;
            &lt;span class=&quot;f6 color-text-tertiary no-wrap ml-1&quot;&gt;
              &lt;relative-time datetime=&quot;2021-05-16T10:52:51Z&quot; class=&quot;no-wrap&quot;&gt;May 16, 2021&lt;/relative-time&gt;
            &lt;/span&gt;
          &lt;/div&gt;
        &lt;/div&gt;
      &lt;/div&gt;

      &lt;div class=&quot;Box p-3 mt-2&quot;&gt;
        &lt;div&gt;
          &lt;div class=&quot;f4 lh-condensed text-bold color-text-primary&quot;&gt;
            &lt;a class=&quot;Link--primary no-underline text-bold wb-break-all d-inline-block&quot; href=&quot;/SaijoGeorge/ExpandingGridItemAnimation&quot; rel=&quot;noreferrer&quot;&gt;SaijoGeorge/ExpandingGridItemAnimation&lt;/a&gt;
          &lt;/div&gt;
          &lt;div class=&quot;dashboard-break-word color-text-secondary mt-1 mb-0 repo-description&quot;&gt;
            &lt;p&gt;Grid item animation based on the Dribbble shot &quot;Surf Project&quot; by Filip Slováček.&lt;/p&gt;
          &lt;/div&gt;

          &lt;p class=&quot;f6 color-text-secondary mt-2 mb-0&quot;&gt;
              &lt;span class=&quot;d-inline-block color-text-secondary mr-3&quot;&gt;
                &lt;span class=&quot;ml-0&quot;&gt;
  &lt;span class=&quot;repo-language-color&quot; style=&quot;background-color: #f1e05a&quot;&gt;&lt;/span&gt;
  &lt;span itemprop=&quot;programmingLanguage&quot;&gt;JavaScript&lt;/span&gt;
&lt;/span&gt;

              &lt;/span&gt;

              &lt;span class=&quot;d-inline-block mr-3&quot;&gt;
                  &lt;a class=&quot;Link--muted&quot; href=&quot;/SaijoGeorge/ExpandingGridItemAnimation/stargazers&quot; rel=&quot;noreferrer&quot;&gt;&lt;svg class=&quot;octicon octicon-star mr-1&quot; viewBox=&quot;0 0 16 16&quot; version=&quot;1.1&quot; width=&quot;16&quot; height=&quot;16&quot; aria-hidden=&quot;true&quot;&gt;&lt;path fill-rule=&quot;evenodd&quot; d=&quot;M8 .25a.75.75 0 01.673.418l1.882 3.815 4.21.612a.75.75 0 01.416 1.279l-3.046 2.97.719 4.192a.75.75 0 01-1.088.791L8 12.347l-3.766 1.98a.75.75 0 01-1.088-.79l.72-4.194L.818 6.374a.75.75 0 01.416-1.28l4.21-.611L7.327.668A.75.75 0 018 .25zm0 2.445L6.615 5.5a.75.75 0 01-.564.41l-3.097.45 2.24 2.184a.75.75 0 01.216.664l-.528 3.084 2.769-1.456a.75.75 0 01.698 0l2.77 1.456-.53-3.084a.75.75 0 01.216-.664l2.24-2.183-3.096-.45a.75.75 0 01-.564-.41L8 2.694v.001z&quot;&gt;&lt;/path&gt;&lt;/svg&gt;9&lt;/a&gt;
              &lt;/span&gt;


              &lt;span&gt;Updated May 16&lt;/span&gt;
          &lt;/p&gt;
        &lt;/div&gt;
      &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;&lt;/div&gt;</content>
  </entry>
</feed>

**Comment by evert** [comment]
@akubaragas if you had a real comment, it got really messed up

**Comment by TheRealPoppy133** [comment]
> When parsing XML like the following:
> 
> `<?xml version="1.0" encoding="UTF-8"?> <entry xmlns="http://www.w3.org/2005/Atom"> <media:content xmlns:media="http://search.yahoo.com/mrss/" url="https://some-url.com?AWSAccessKeyId=XYZ&amp;Expires=1531998005&amp;Signature=XYZ%3D" type="video/mp4" medium="video"> <media:hash algo="md5">XYZ</media:hash> </media:content><media:thumbnail xmlns:media="http://search.yahoo.com/mrss/" url="https://some-url.com/image/xyz.jpg" width="1755" height="987"/> </entry>`
> 
> I noticed that the XML elements directly following the closure of **<media:content** get ignored and do not get parsed.
> 
> If I put a space or a new line right after the closure of **<media:content**, parsing for XML elements that follow works again.
> 
> In my example above, the **<media:thumbnail** element would not get parsed at all.
> 
> If I put a space or a new line before **<media:thumbnail** it gets parsed properly.
> 
> I tried replacing **<media:thumbnail** with other XML elements, the behaviour is the same.

**Comment by Pob1212** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xml:lang="en-US">
  <id>tag:github.com,2008:/Pob1212</id>
  <link type="text/html" rel="alternate" href="https://github.com/Pob1212"/>
  <link type="application/atom+xml" rel="self" href="https://github.com/Pob1212.private.atom?token=AVMCCTE6BCS5BBYV6UE7CGF7LDCUY"/>
  <title>ฟีดส่วนตัวสำหรับ Pob1212</title>
  <updated>2021-08-28T02:05:17+07:00</updated>
</feed>

**Comment by Pob1212** [comment]
> tag:github.com,2008:/Pob1212 <title>ยินดีต้อนรับสำหรับ Pob1212</title> 2021-08-28T02:05:17+07:00

**Comment by SMG82** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xml:lang="en-US">
  <id>tag:github.com,2008:/SMG82</id>
  <link type="text/html" rel="alternate" href="https://github.com/SMG82"/>
  <link type="application/atom+xml" rel="self" href="https://github.com/SMG82.private.atom?token=AWKI2W2MRENQK6MDCZCFEDF7RWFCQ"/>
  <title>Private Feed for SMG82</title>
  <updated>2021-11-02T21:08:37+00:00</updated>
</feed>

**Comment by evert** [comment]
@SMG82 @Pob1212 your comments are meaningless. What are you hoping to achieve?

Maybe im replying to bots so I'm considering locking this thread.

**Comment by Lippertt** [comment]
> Ao analisar XML como o seguinte:
> 
> `<?xml version="1.0" encoding="UTF-8"?> <entry xmlns="http://www.w3.org/2005/Atom"> <media:content xmlns:media="http://search.yahoo.com/mrss/" url="https://some-url.com?AWSAccessKeyId=XYZ&amp;Expires=1531998005&amp;Signature=XYZ%3D" type="video/mp4" medium="video"> <media:hash algo="md5">XYZ</media:hash> </media:content><media:thumbnail xmlns:media="http://search.yahoo.com/mrss/" url="https://some-url.com/image/xyz.jpg" width="1755" height="987"/> </entry>`
> 
> Percebi que os elementos XML diretamente após o fechamento de **<media:content** são ignorados e não são analisados.
> 
> Se eu colocar um espaço ou uma nova linha logo após o fechamento de **<media:content** , a análise dos elementos XML a seguir funcionará novamente.
> 
> No meu exemplo acima, o elemento **<media:thumbnail** não seria analisado.
> 
> Se eu colocar um espaço ou uma nova linha antes de **<media:thumbnail** , ela será analisada corretamente.
> 
> Tentei substituir **<media:thumbnail** por outros elementos XML, o comportamento é o mesmo.
