### ISSUE TITLE
Root Element Read

### ISSUE THREAD

**Issue by victorgp89** [sabre-io/xml#162]
Hi,
It's possible to read the name of the root element? 

```xml
<?xml version="1.0" encoding="utf-8"?>
<GetHotelInfoRQ>
	<User>TestUser</User>
	<Password>TestPass</Password>
	<HotelCode>3403</HotelCode>
</GetHotelInfoRQ>
```

If I have this xml when a call parse method the root element dissapear.

Thanks for advance.

**Comment by evert** [comment]
Hi @victorgp89 ,

Can you share the code you are using to parse this? It will make it easier to answer the question,

**Comment by evert** [comment]
No response
