### ISSUE TITLE
Parsing large xml files

### ISSUE THREAD

**Issue by VinceG** [sabre-io/xml#164]
looks like when we attempt to read a large xml file it throws an error similar to this

xmlSAX2Characters: huge text node on line 1, column 10000901

any way to enable to parse large xml files? Similar to simple xml LIBXML_PARSEHUGE option?

**Comment by evert** [comment]
Hi @VinceG ,

You're probably using the `Service` class, which sets up the XML reader and writer.
Probably the best way to do this right now is to either:

1. Construct your own XML\Reader class manually so you can pass these options to `read()` yourself.
2. Subclass the `Service` class and override the `->parse` functions so you get a chance to add these settings.

I can see that it would make sense to provide a way in the Service class to define which options get passed to `read()`, so I'll keep this open as a feature requests. PR's welcome.

**Comment by VinceG** [comment]
@evert  I am actually using the Reader. Example:

```
$reader = new Reader();
$reader->xml($client->soap()->__getLastRequest());
$result = $reader->parse();
```

I wasn't able to find anything in the docs to pass in additional options. Also it looks like it's failing on the deserialize portion of the reading process.

Will you be able to quickly let me know what options i need to pass in in order to be able to parse large xml files?

Thank You.

**Comment by evert** [comment]
Yep you can =)

**Comment by evert** [comment]
Since this was solved for you, I'm gonna close this ticket

**Comment by VinceG** [comment]
@evert Perfect, thank you.

We also use the Service in another place and there i can't modify the xml() method. Will you be open to a PR to add forth argument to the following method:

https://github.com/sabre-io/xml/blob/master/lib/Service.php#L105

which will be the LIB_* options?

**Comment by evert** [comment]
Yes, open to a PR and would prefer a public class property that defaults to 0.
