### ISSUE TITLE
no xmlns

### ISSUE THREAD

**Issue by z1912774711** [sabre-io/xml#170]
![TIM截图20200118150350](https://user-images.githubusercontent.com/44776918/72660092-c2754680-3a03-11ea-9922-1c7e2320793a.png)
How can I get rid of it '{}'

**Comment by z1912774711** [comment]
![TIM截图20200118150634](https://user-images.githubusercontent.com/44776918/72660120-2992fb00-3a04-11ea-982f-52b9de9c9d05.png)

**Comment by tsterker** [comment]
@z1912774711 It's really worth reading the [documentation](https://sabre.io/xml/), which addresses common use cases and has many examples.

To strip namespaces, you can use the `keyValue` deserializer and specify the namespace, as described [here](https://sabre.io/xml/reading/#stripping-the-xml-namespaces). In your case, I assume you could pass in an empty string:

```php
$service = new Sabre\Xml\Service();
$service->elementMap = [
    '{}item' => function(Sabre\Xml\Reader $reader) {
        return Sabre\Xml\Deserializer\keyValue($reader, '');
    }
];

print_r($service->parse($xml));
```

**Comment by staabm** [comment]
Closing, feel free to discuss the reported problem further, though
