### ISSUE TITLE
I can't seem to get the right codes sent to me for my accounts

### ISSUE THREAD

**Issue by Bin321trin2dowhatsRigHt** [sabre-io/xml#180]
I have tried to email and contact developers and did no good not a reply or anything.

**Comment by evert** [comment]
What exactly are you talking about? I suspect you're in the wrong place, but please explain and maybe we can send you on your way

**Comment by Bin321trin2dowhatsRigHt** [comment]
I have had issues with my devices not letting me sign into my media accounts. Have this thing popping up. Called tracker? Didn't realize my developers settings had gotten turned on and had two figure authentication on on an XR. Which crashed hard after three months of having it. Believe my ex had compermised my settings and made herself the admin over it. I just would like to know why I can't recover my cards and accounts? Or if there's a way to find out who's behind the malisous attack that's wrecked all my settings. After a complete hard reset and reboot still there..

**Comment by evert** [comment]
This project has nothing to do with credit card payments, media, accounts or trackers. It's just a minor library to parse XML.

**Comment by Bin321trin2dowhatsRigHt** [comment]
I didnt know? Sorry to bother or if I messed anything up I apologise. Thinks for the insite. Thought this would help just following hiden leads on my device. I have had troubles figuring it all out not to tech savvy cars and houses that I can fix .

**Comment by evert** [comment]
No worries. Maybe you're looking for a company with a similar name. Hope you figure it out!
