### ISSUE TITLE
Allowed memory size exhausted when writing

### ISSUE THREAD

**Issue by david-kristin** [sabre-io/xml#186]
I use the Service for writing XML, it look like this:

`$this->service->write('rss', [
  'channel' => $channel,
])`

The channel is composed of thousands of items, thus I am getting `Allowed memory size of 134217728 bytes exhausted (tried to allocate 171570808 bytes)` that is related to `$w->outputMemory()` line.

How can this be solved? Generally, the problem is writing a huge text.

**Comment by evert** [comment]
The services work with the XMLWriter to output a string by default. If you skip the Service class and work with `Writer` directly, you can use `openURI` on the writer instead to write directly to a stream.

This method should take `php://output` as an argument I believe.

**Comment by david-kristin** [comment]
Thank you so much, evert. Otherwise I would be stuck on this one much longer.
