### ISSUE TITLE
bump min php versions

### ISSUE THREAD

**Issue by staabm** [sabre-io/xml#215]
I think we should strip down the supported php version matrix

what do you guys think about dropping at least 7.1/7.2 ?

see https://www.php.net/supported-versions.php

**Comment by phil-davis** [comment]
IMO just support PHP 7.3 and up. 
7.3 has been out of official support for security patches since late last year (about 7 months ago now). Maybe support for 7.3 can be dropped around the end of this year?

One benefit of dropping the older minor versions of PHP is that gradually more parameter and return types can be used, and new functions relied-on etc.

**Comment by tacman** [comment]
Since 7.3 is at EOL, what about bumping the version and requiring 7.4?  Typed properties in classes are great, among other things.

**Comment by phil-davis** [comment]
> Since 7.3 is at EOL, what about bumping the version and requiring 7.4? Typed properties in classes are great, among other things.

Yes, we are about at that point anyway. Various consumers of these sabre-io repos that I am familiar with have either dropped, or are soon to drop, PHP 7.3 support. 

We could make a branch from current master that can keep the current PHP support and if any interesting/critical/security patches are needed then we can backport patches to that branch. And then in master develop PHP 7.4+ code, put all the possible type declarations in parameters, function returns, variables, removing deprecated stuff... and release as a new major version. That avoids the need to think hard about strict backward-compatibility for methods of classes etc that start having stricter formal interfaces, and for which there could be implementations that extend the class and now have to also add the types.

For the future, some time in 2023, we can discuss dropping PHP 7.4. And that may or may not cause another major version bump, depending on what extra things happened in PHP 8.0+ that are not available in PHP 7.4. But that can be a separate discussion.

**Comment by staabm** [comment]
Agree 👍

**Comment by phil-davis** [comment]
Major version 3 https://github.com/sabre-io/xml/releases/tag/3.0.0 has been released here.
https://github.com/sabre-io/uri has minor release https://github.com/sabre-io/uri/releases/tag/2.3.0 - there was no need to cause a BC-break there, so no need for a major version bump.

I am looking at vobject now. I will leave this issue open, and update as I progress up the tree to finally get sabre/dav sorted out.

**Comment by DeepDiver1975** [comment]
7.4 is min -> close
