### ISSUE TITLE
PHPstan error reported for startElementNs call

### ISSUE THREAD

**Issue by phil-davis** [sabre-io/xml#227]
phpstan reports:
```
------ ------------------------------------------------------------------------------------------- 
  Line   lib/Writer.php                                                                             
 ------ ------------------------------------------------------------------------------------------- 
  132    Parameter #3 $namespace of method XMLWriter::startElementNs() expects string, null given.  
 ------ ------------------------------------------------------------------------------------------- 
```

But https://www.php.net/manual/en/xmlwriter.startelementns.php documents the 3rd parameter as `?string` - if I leave out the 3rd parameter, then PHPstan complains that it must be given - correct. But if I specify it as `null` then PHPstan also complains.

What code is supposed to be written?

**Comment by staabm** [comment]
fixed with https://github.com/phpstan/phpstan-src/pull/1772
